In [1]:
import sys
import os
print os.getcwd()
sys.path.append("C:\Users\shubhangi\Documents\GitHub\YelpSA\lib")
import numpy as np
import pre_processing as pp
import feature_select as fs
import logistic_classifier as log_clf
from sklearn.metrics import confusion_matrix
import copy
import naive_bayes_classifier as nb
import ensemble_classifier as en

C:\Users\shubhangi


In [2]:
def get_ylabels(y_test):
    y_test_thresholded_ternary = np.array(copy.deepcopy(y_test))
    y_test_thresholded_ternary[y_test_thresholded_ternary < 3] = 0
    y_test_thresholded_ternary[y_test_thresholded_ternary == 3] = 1
    y_test_thresholded_ternary[y_test_thresholded_ternary > 3] = 2
    
    y_test_thresholded_binary = np.array(copy.deepcopy(y_test))
    y_test_thresholded_binary[y_test_thresholded_binary < 3] = 0
    y_test_thresholded_binary[y_test_thresholded_binary >= 3] = 1
    
    return [y_test, y_test_thresholded_binary, y_test_thresholded_ternary]

In [2]:
#Preprocess
[preprocessed_data_sample, labels_sample, vectorizer, no_features, samples, unvectorized_data_sample] = pp.preprocess()
data_sample_copy = (preprocessed_data_sample)


C:\Users\shubhangi\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2825: DtypeWarning: Columns (1,4,7,17,26,29,49,60,62,79,86,94) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


20000
stemming 
length of vocabulary 942


In [ ]:
#fs.feature_selection(labels_sample, np.array(unvectorized_data_sample))

In [3]:
#[preprocessed_data_sample, labels_sample, vectorizer, no_features, samples, unvectorized_data_sample] = pp.preprocess()

#Dividing samples into train and test
train_plus_test = samples#20000#(train_length + test_length) * 3#20000
ratio = int(train_plus_test * 0.7)

X_train = preprocessed_data_sample[0:ratio]
y_train = labels_sample[0:ratio]
X_test = preprocessed_data_sample[ratio:train_plus_test]
y_test = labels_sample[ratio:train_plus_test]

#print id(y_test)

no_classes = 5


C:\Users\shubhangi\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2825: DtypeWarning: Columns (1,4,7,17,26,29,49,60,62,79,86,94) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


20000
stemming 
length of vocabulary 942
67610720


In [ ]:
#Train logistic regression
w = clf.train_logistic_regression(X_train, y_train, no_classes)

In [10]:
#Thresholding labels
#To compute train accuracy if necessary
y_train_thresholded = np.array(copy.deepcopy(y_train))
y_train_thresholded[y_train_thresholded < 3] = 0
y_train_thresholded[y_train_thresholded == 3] = 1
y_train_thresholded[y_train_thresholded > 3] = 2
print len(y_test)
[y_test, y_test_thresholded_binary, y_test_thresholded_ternary] = get_ylabels(y_test)

#print (y_test_thresholded)
[pred, prob] = log_clf.predict(w, X_test)
print "Logistic 5 class accuracy", (sum(pred==y_test) * 100.0 / len(y_test))
print "Confusion matrix\n", confusion_matrix(y_test, pred)

[pred_lr, prob_lr] = log_clf.predict_ternary(w, X_test)
print "Logistic 3 class accuracy", (sum(pred_lr==y_test_thresholded_ternary) * 100.0 / len(y_test_thresholded_ternary))
print "Confusion matrix\n", confusion_matrix(y_test_thresholded_ternary, pred_lr)

[pred, prob] = log_clf.predict_binary(w, X_test)
print "Logistic 2 class accuracy", (sum(pred==y_test_thresholded_binary) * 100.0 / len(y_test_thresholded_binary))
print "Confusion matrix\n", confusion_matrix(y_test_thresholded_binary, pred)

[pred, prob] = log_clf.predict(w, X_train)
print "Logistic 5 class accuracy", (sum(pred==y_train) * 100.0 / len(y_train))
print "Confusion matrix\n", confusion_matrix(y_train, pred)

[pred, prob] = log_clf.predict_ternary(w, X_train)
print "Logistic 3 class accuracy", (sum(pred==y_train_thresholded) * 100.0 / len(y_train_thresholded))
print "Confusion matrix\n", confusion_matrix(y_train_thresholded, pred)

y_train_thresholded = np.array(copy.deepcopy(y_train))
y_train_thresholded[y_train_thresholded < 3] = 0
y_train_thresholded[y_train_thresholded >= 3] = 1

[pred, prob] = log_clf.predict_binary(w, X_train)
print "Logistic 2 class accuracy", (sum(pred==y_train_thresholded) * 100.0 / len(y_train_thresholded))
print "Confusion matrix\n", confusion_matrix(y_train_thresholded, pred)

6000
Logistic 5 class accuracy 50.9166666667
Confusion matrix
[[ 373  112   53   45   51]
 [ 136  176  165  110   68]
 [  50   88  309  404  117]
 [  34   41  208  967  685]
 [  25   26   43  484 1230]]
Logistic 3 class accuracy 74.5333333333
Confusion matrix
[[ 797  218  274]
 [ 138  309  521]
 [ 126  251 3366]]
Logistic 2 class accuracy 87.4
Confusion matrix
[[ 797  492]
 [ 264 4447]]
Logistic 5 class accuracy 61.6571428571
Confusion matrix
[[1005  181   78   78   77]
 [ 262  690  311  197  126]
 [  89  173 1034  738  281]
 [  54   67  310 2649 1293]
 [  31   35   88  899 3254]]
Logistic 3 class accuracy 80.4785714286
Confusion matrix
[[2138  389  478]
 [ 262 1034 1019]
 [ 187  398 8095]]
Logistic 2 class accuracy 90.6
Confusion matrix
[[ 2138   867]
 [  449 10546]]


Naive Bayes


In [11]:
import naive_bayes_classifier as nb
no_classes = 5
#no_features = 942

w, prior = nb.train(X_train, y_train, no_classes)
print w

[[  3.49389363e-04   1.01640542e-03   2.22338685e-04 ...,   1.11169343e-03
    2.85864024e-04   3.49389363e-04]
 [  7.04272141e-04   8.10577370e-04   6.11255066e-04 ...,   1.62115474e-03
    2.52474919e-04   4.78373530e-04]
 [  6.30011455e-04   1.39366170e-03   1.03092784e-03 ...,   2.41504391e-03
    4.77281405e-05   6.30011455e-04]
 [  8.78749568e-04   9.92136609e-04   1.30395097e-03 ...,   3.75311106e-03
    2.26774082e-05   4.98902980e-04]
 [  8.22101402e-04   7.87559326e-04   9.60269705e-04 ...,   4.35920995e-03
    2.76336606e-05   2.62519775e-04]]


In [ ]:
#Predicting on naive bayes
pred, prob_normal = nb.predict(X_test, w_nb, prior)
c = confusion_matrix(pred, y_test)
print "5 class classification naive bayes"
print c
accuracy = sum(pred==y_test) * 100.0 / len(y_test)
print accuracy

[y_test, y_test_thresholded_binary, y_test_thresholded_ternary] = get_ylabels(y_test)

pred, prob = nb.pred_binary(X_test, w_nb, prior)
print "2 class classification naive bayes"
print confusion_matrix(pred, y_test_thresholded_binary)
accuracy = sum(pred==y_test_thresholded_binary) * 100.0 / len(y_test)
print accuracy

pred, prob = nb.pred_ternary(X_test, w_nb, prior)
print "3 class classification naive bayes"
print confusion_matrix(y_test_thresholded_ternary, pred)
accuracy = sum(pred==y_test_thresholded_ternary) * 100.0 / len(y_test)
print accuracy

In [4]:
#Ensemble classifier
#import ensemble_classifier as en
no_classes = 5
w_lr, prior, w_nb = en.train(X_train, y_train, no_classes)

[[  3.49389363e-04   1.01640542e-03   2.22338685e-04 ...,   1.11169343e-03
    2.85864024e-04   3.49389363e-04]
 [  7.04272141e-04   8.10577370e-04   6.11255066e-04 ...,   1.62115474e-03
    2.52474919e-04   4.78373530e-04]
 [  6.30011455e-04   1.39366170e-03   1.03092784e-03 ...,   2.41504391e-03
    4.77281405e-05   6.30011455e-04]
 [  8.78749568e-04   9.92136609e-04   1.30395097e-03 ...,   3.75311106e-03
    2.26774082e-05   4.98902980e-04]
 [  8.22101402e-04   7.87559326e-04   9.60269705e-04 ...,   4.35920995e-03
    2.76336606e-05   2.62519775e-04]]
init [[  3.49389363e-04   1.01640542e-03   2.22338685e-04 ...,   1.11169343e-03
    2.85864024e-04   3.49389363e-04]
 [  7.04272141e-04   8.10577370e-04   6.11255066e-04 ...,   1.62115474e-03
    2.52474919e-04   4.78373530e-04]
 [  6.30011455e-04   1.39366170e-03   1.03092784e-03 ...,   2.41504391e-03
    4.77281405e-05   6.30011455e-04]
 [  8.78749568e-04   9.92136609e-04   1.30395097e-03 ...,   3.75311106e-03
    2.26774082e-05   4.

In [8]:
#import ensemble_classifier as en2
#import logistic_classifier as log_clf
#import naive_bayes_classifier as nb
pred = en.predict_ternary(X_test, w_lr, w_nb, prior)

[y_test, y_test_thresholded_binary, y_test_thresholded_ternary] = get_ylabels(y_test)
print confusion_matrix(y_test_thresholded_ternary, pred)
accuracy = sum(pred==y_test_thresholded_ternary) * 100.0 / len(y_test)
print accuracy



(6000L, 5L)
[]
0
[[ 924  185  180]
 [ 200  336  432]
 [ 170  283 3290]]
75.8333333333


In [9]:
pred = en.predict_binary(X_test, w_lr, w_nb, prior)
print confusion_matrix(y_test_thresholded_binary, pred)
accuracy = sum(pred==y_test_thresholded_binary) * 100.0 / len(y_test)
print accuracy

pred = en.predict(X_test, w_lr, w_nb, prior)
print confusion_matrix(y_test, pred)
accuracy = sum(pred==y_test) * 100.0 / len(y_test)
print accuracy

(6000L, 5L)
[]
0
[[ 902  387]
 [ 337 4374]]
87.9333333333
(6000L, 5L)
[]
0
[[ 425  108   35   30   36]
 [ 145  222  164   87   37]
 [  58  139  354  328   89]
 [  43   65  254  903  670]
 [  30   34   49  443 1252]]
52.6
